tpl2dox demo: PARAMETER_SECTION
PARAMETER_SECTION
Variables
sdreport_number avg_F
matrix C (1, nyrs, 1, nages)
init_bounded_dev_vector effort_devs (1, nyrs,-5., 5., 3)
matrix F (1, nyrs, 1, nages)
objective_function_value f
number initsum
vector log_initpop (1, nyrs+nages-1)
init_number log_popscale (1)
init_number log_q (1)
init_bounded_dev_vector log_relpop (1, nyrs+nages-1,-15., 15., 2)
vector log_sel (1, nages)
init_bounded_dev_vector log_sel_coff (1, nages-1,-15., 15., 2)
matrix N (1, nyrs, 1, nages)
likeprof_number pred_B
sdreport_vector predicted_N (2, nages)
sdreport_vector ratio_N (2, nages)
number recsum
matrix S (1, nyrs, 1, nages)
matrix Z (1, nyrs, 1, nages)
Detailed Description
Variable Documentation
sdreport_number avg_F
Definition at line 285 of file catage.tpl.
matrix C(1, nyrs, 1, nages)
Referenced by evaluate_the_objective_function(), and get_catch_at_age().
init_bounded_dev_vector effort_devs(1, nyrs,-5., 5., 3)
Referenced by evaluate_the_objective_function(), and get_mortality_and_survivial_rates().
matrix F(1, nyrs, 1, nages)
Referenced by evaluate_the_objective_function(), get_catch_at_age(), and get_mortality_and_survivial_rates().
objective_function_value f
Definition at line 282 of file catage.tpl.
number initsum
Definition at line 284 of file catage.tpl.
vector log_initpop(1, nyrs+nages-1)
Referenced by get_numbers_at_age().
init_number log_popscale(1)
Referenced by get_numbers_at_age().
init_number log_q(1)
Referenced by get_mortality_and_survivial_rates().
init_bounded_dev_vector log_relpop(1, nyrs+nages-1,-15., 15., 2)
Referenced by evaluate_the_objective_function(), and get_numbers_at_age().
vector log_sel(1, nages)
Referenced by get_mortality_and_survivial_rates().
init_bounded_dev_vector log_sel_coff(1, nages-1,-15., 15., 2)
Referenced by get_mortality_and_survivial_rates().
matrix N(1, nyrs, 1, nages)
Referenced by get_catch_at_age(), and get_numbers_at_age().
likeprof_number pred_B
Definition at line 290 of file catage.tpl.
sdreport_vector predicted_N(2, nages)
Referenced by get_numbers_at_age().
sdreport_vector ratio_N(2, nages)
Referenced by get_numbers_at_age().
number recsum
Definition at line 283 of file catage.tpl.
matrix S(1, nyrs, 1, nages)
Referenced by get_catch_at_age(), get_mortality_and_survivial_rates(), and get_numbers_at_age().
matrix Z(1, nyrs, 1, nages)
Referenced by get_catch_at_age(), and get_mortality_and_survivial_rates().