tpl2dox demo: tpl FUNCTIONS
tpl FUNCTIONS
Classes
class model_data
class model_parameters
Functions
calculate_biomass_and_predicted_catch ()
calculate_fishing_mortality ()
calculate the fishing mortality.
calculate_the_objective_function ()
Variables
double avg_effort =mean(effort)
beta
cpue =column(data,3)
effort =elem_div(obs_catch,cpue)
m
obs_catch =column(data,2)
r
Detailed Description
FUNCTIONS declared in the tpl PROCEDURE_SECTION.
Function Documentation
void model_parameters::calculate_biomass_and_predicted_catch (void)
Definition at line 137 of file pella-t.tpl.
References model_parameters::B_projected, model_parameters::beta(), model_parameters::binit, model_parameters::bio_tmp, model_parameters::biomass(), model_parameters::c_tmp, model_data::effort(), model_parameters::f(), model_parameters::k(), model_parameters::k_1, model_parameters::k_change, model_parameters::k_devs(), model_parameters::k_last, model_parameters::k_ratio, model_parameters::log_binit(), model_parameters::m(), model_data::nobs, model_data::obs_catch(), model_parameters::pred_catch(), model_parameters::q(), and model_parameters::r().
void model_parameters::calculate_fishing_mortality (void)
calculate the fishing mortality.
Definition at line 129 of file pella-t.tpl.
References model_data::effort(), model_parameters::effort_devs(), model_parameters::f(), and model_parameters::q().
void model_parameters::calculate_the_objective_function (void)
Definition at line 196 of file pella-t.tpl.
References model_parameters::effort_devs(), model_parameters::f(), model_parameters::ff, model_parameters::k_devs(), model_parameters::m(), model_data::nobs, model_data::obs_catch(), and model_parameters::pred_catch().
Variable Documentation
double avg_effort =mean(effort)
Definition at line 109 of file pella-t.tpl.
beta
Definition at line 65 of file pella-t.tpl.
cpue =column(data,3)
Definition at line 105 of file pella-t.tpl.
effort =elem_div(obs_catch,cpue)
Definition at line 107 of file pella-t.tpl.
m
Definition at line 64 of file pella-t.tpl.
obs_catch =column(data,2)
Definition at line 104 of file pella-t.tpl.
r
Definition at line 66 of file pella-t.tpl.